sudo: require
services:
  - docker

before_install:
  - docker build -t kdekic/react-test -f ./client/Dockerfile.dev ./client 
  
script:
  - docker run -e CI=true kdekic/react-test npm test

after_success:
  - docker build -t kdekic/multi-client ./client
  - docker build -t kdekic/multi-nginx ./nginx
  - docker build -t kdekic/multi-server ./server
  - docker build -t kdekic/multi-worker ./worker
