sudo: require
services:
  - docker

before_install:
  - docker build -t kdekic/react-test -f ./client/Dockerfile.dev ./client 
  
script:
  - docker run -e CI=true kdekic/react-test npm test

after_success:
  - docker build -t kdekic/multi-client ./client
  - docker build -t kdekic/multi-nginx ./nginx
  - docker build -t kdekic/multi-server ./server
  - docker build -t kdekic/multi-worker ./worker

# Log in to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Take those images and push them to docker hub
 - docker push kdekic/multi-client
 - docker push kdekic/multi-nginx
 - docker push kdekic/multi-server
 - docker push kdekic/multi-worker
 